//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckEngineTaller.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTallerEntities2 : DbContext
    {
        public DBTallerEntities2()
            : base("name=DBTallerEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Actividad> T_Actividad { get; set; }
        public virtual DbSet<T_Bitacora> T_Bitacora { get; set; }
        public virtual DbSet<T_Caja> T_Caja { get; set; }
        public virtual DbSet<T_Cliente> T_Cliente { get; set; }
        public virtual DbSet<T_Detallefactura> T_Detallefactura { get; set; }
        public virtual DbSet<T_Empleado> T_Empleado { get; set; }
        public virtual DbSet<T_Estacion> T_Estacion { get; set; }
        public virtual DbSet<T_Factura> T_Factura { get; set; }
        public virtual DbSet<T_Gastos> T_Gastos { get; set; }
        public virtual DbSet<T_Manodeobra> T_Manodeobra { get; set; }
        public virtual DbSet<T_Mecanico> T_Mecanico { get; set; }
        public virtual DbSet<T_Pago> T_Pago { get; set; }
        public virtual DbSet<T_Pedido> T_Pedido { get; set; }
        public virtual DbSet<T_Producto> T_Producto { get; set; }
        public virtual DbSet<T_Proveedores> T_Proveedores { get; set; }
        public virtual DbSet<T_Proyecto> T_Proyecto { get; set; }
        public virtual DbSet<T_Vehiculo> T_Vehiculo { get; set; }
    }
}
