//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckEngineTaller.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Actividad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Actividad()
        {
            this.T_Estacion = new HashSet<T_Estacion>();
        }
    
        public string Ac_Descripcion { get; set; }
        public string Ac_Nombre { get; set; }
        public int Ac_Id { get; set; }
        public int M_Id { get; set; }
        public Nullable<int> Pr_Id { get; set; }
        public Nullable<int> Pr_Cantidad { get; set; }
    
        public virtual T_Producto T_Producto { get; set; }
        public virtual T_Mecanico T_Mecanico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Estacion> T_Estacion { get; set; }
    }
}
