//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckEngineTaller.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Bitacora
    {
        public int B_Id { get; set; }
        public string B_Formulario { get; set; }
        public string B_Funcion { get; set; }
        public int B_Llave { get; set; }
        public int E_Id { get; set; }
    
        public virtual T_Empleado T_Empleado { get; set; }
    }
}
