//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckEngineTaller.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Cliente()
        {
            this.T_Vehiculo = new HashSet<T_Vehiculo>();
        }
    
        public string CI_Direccion { get; set; }
        public string CI_Identificacion { get; set; }
        public string CI_Nombre1 { get; set; }
        public string CI_Nombre2 { get; set; }
        public string CI_Apellido1 { get; set; }
        public string CI_Apellido2 { get; set; }
        public string CI_Telefono { get; set; }
        public int CI_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Vehiculo> T_Vehiculo { get; set; }
    }
}
