//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckEngineTaller.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Detallefactura
    {
        public int Pr_Id { get; set; }
        public int Mdo_Id { get; set; }
        public int DF_Cantidad { get; set; }
        public int C_Id { get; set; }
        public int Fc_id { get; set; }
    
        public virtual T_Factura T_Factura { get; set; }
        public virtual T_Manodeobra T_Manodeobra { get; set; }
        public virtual T_Producto T_Producto { get; set; }
    }
}
