//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckEngineTaller.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Gastos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Gastos()
        {
            this.T_Pago = new HashSet<T_Pago>();
        }
    
        public Nullable<int> E_Id { get; set; }
        public Nullable<int> Pd_Id { get; set; }
        public Nullable<int> G_FacturaID { get; set; }
        public bool G_Estado { get; set; }
        public int G_Id { get; set; }
    
        public virtual T_Empleado T_Empleado { get; set; }
        public virtual T_Pedido T_Pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Pago> T_Pago { get; set; }
    }
}
