//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckEngineTaller.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Gastos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Gastos()
        {
            this.T_Pago = new HashSet<T_Pago>();
        }
    
        public Nullable<int> E_Id { get; set; }
        public Nullable<int> Pd_Id { get; set; }
        public Nullable<int> G_FacturaID { get; set; }
        public bool G_Estado { get; set; }
        public int G_Id { get; set; }
    
        public virtual T_Empleado T_Empleado { get; set; }
        public virtual T_Pedido T_Pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Pago> T_Pago { get; set; }
    }
}
