//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckEngineTaller.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Pago
    {
        public int G_Id { get; set; }
        public int C_Id { get; set; }
        public decimal Pag_Cantidad { get; set; }
    
        public virtual T_Caja T_Caja { get; set; }
        public virtual T_Gastos T_Gastos { get; set; }
    }
}
