//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckEngineTaller.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Pago
    {
        public int G_Id { get; set; }
        public int C_Id { get; set; }
        public decimal Pag_Cantidad { get; set; }
    
        public virtual T_Caja T_Caja { get; set; }
        public virtual T_Gastos T_Gastos { get; set; }
    }
}
