//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckEngineTaller.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Pedido()
        {
            this.T_Gastos = new HashSet<T_Gastos>();
        }
    
        public int Pd_Id { get; set; }
        public int Pr_Id { get; set; }
        public int Pd_Cantidad { get; set; }
        public string Pd_Descripcion { get; set; }
        public decimal Pd_PrecioUnitario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Gastos> T_Gastos { get; set; }
        public virtual T_Producto T_Producto { get; set; }
    }
}
