//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckEngineTaller.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Pedido()
        {
            this.T_Gastos = new HashSet<T_Gastos>();
        }
    
        public int Pd_Id { get; set; }
        public int Pr_Id { get; set; }
        public int Pd_Cantidad { get; set; }
        public string Pd_Descripcion { get; set; }
        public decimal Pd_PrecioUnitario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Gastos> T_Gastos { get; set; }
        public virtual T_Producto T_Producto { get; set; }
    }
}
