//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckEngineTaller.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Proyecto
    {
        public int Es_Id { get; set; }
        public int Mdo_Id { get; set; }
        public int Pry_Id { get; set; }
        public int V_id { get; set; }
        public string Pry_Comentario { get; set; }
    
        public virtual T_Estacion T_Estacion { get; set; }
        public virtual T_Manodeobra T_Manodeobra { get; set; }
        public virtual T_Vehiculo T_Vehiculo { get; set; }
    }
}
