//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckEngineTaller.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Producto()
        {
            this.T_Actividad = new HashSet<T_Actividad>();
            this.T_Detallefactura = new HashSet<T_Detallefactura>();
            this.T_Pedido = new HashSet<T_Pedido>();
        }
    
        public int Pr_Id { get; set; }
        public int P_Id { get; set; }
        public int Pr_CodigoRefaccion { get; set; }
        public string Pr_Descripcion { get; set; }
        public int Pr_Existencia { get; set; }
        public string Pr_Marca { get; set; }
        public string Pr_Nombre { get; set; }
        public decimal Pr_PrecioUnitario { get; set; }
        public decimal Pr_Descuento { get; set; }
        public int Pr_ExistenciaMin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Actividad> T_Actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Detallefactura> T_Detallefactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Pedido> T_Pedido { get; set; }
        public virtual T_Proveedores T_Proveedores { get; set; }
    }
}
