//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckEngineTaller.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Proyecto
    {
        public int Es_Id { get; set; }
        public int Mdo_Id { get; set; }
        public int Pry_Id { get; set; }
        public int V_id { get; set; }
        public string Pry_Comentario { get; set; }
    
        public virtual T_Estacion T_Estacion { get; set; }
        public virtual T_Manodeobra T_Manodeobra { get; set; }
        public virtual T_Vehiculo T_Vehiculo { get; set; }
    }
}
