//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckEngineTaller.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Vehiculo()
        {
            this.T_Proyecto = new HashSet<T_Proyecto>();
        }
    
        public int CI_ID { get; set; }
        public int V_ID { get; set; }
        public string V_Color { get; set; }
        public string V_Estado { get; set; }
        public string V_Marca { get; set; }
        public string V_Modelo { get; set; }
        public string V_Placa { get; set; }
    
        public virtual T_Cliente T_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Proyecto> T_Proyecto { get; set; }
    }
}
